groups:
 - name: Deployment
   rules:
   - alert: Deployment at 0 Replicas for devops team
     annotations:
       summary: Deployment {{$labels.deployment}} is currently having no pods running
       description: "\nCluster Name: {{$externalLabels.cluster}}\nNamespace: {{$labels.namespace}}\nDeployment name: {{$labels.deployment}}\n" 
     expr: |
       sum(kube_deployment_status_replicas{pod_template_hash="", deployment=~"devops.*"}) by (deployment,namespace)  < 1
     for: 2m
     labels:
       tech_team: devops_team

   - alert: Deployment at 0 Replicas for devops team
     annotations:
       summary: Deployment {{$labels.deployment}} is currently having no pods running
       description: "\nCluster Name: {{$externalLabels.cluster}}\nNamespace: {{$labels.namespace}}\nDeployment name: {{$labels.deployment}}\n" 
     expr: |
       sum(kube_deployment_status_replicas{pod_template_hash="", deployment=~"devops.*"}) by (deployment,namespace)  < 1
     for: 2m
     labels:
       tech_team: devops_team

   - alert: HPA Scaling Limited for devops team
     annotations: 
       summary: HPA named {{$labels.hpa}} in {{$labels.namespace}} namespace has reached scaling limited state
       description: "\nCluster Name: {{$externalLabels.cluster}}\nNamespace: {{$labels.namespace}}\nHPA name: {{$labels.hpa}}\n" 
     expr: |
       (sum(kube_hpa_status_condition{condition="ScalingLimited",status="true",hpa=~"devops.*"}) by (hpa,namespace)) == 1
     for: 1m
     labels: 
       tech_team: devops_team

   - alert: HPA Scaling Limited for devops team
     annotations: 
       summary: HPA named {{$labels.hpa}} in {{$labels.namespace}} namespace has reached scaling limited state
       description: "\nCluster Name: {{$externalLabels.cluster}}\nNamespace: {{$labels.namespace}}\nHPA name: {{$labels.hpa}}\n" 
     expr: |
       (sum(kube_hpa_status_condition{condition="ScalingLimited",status="true",hpa=~"devops.*"}) by (hpa,namespace)) == 1
     for: 1m
     labels: 
       tech_team: devops_team
      

   - alert: HPA at MaxCapacity for devops team
     annotations: 
       summary: HPA named {{$labels.hpa}} in {{$labels.namespace}} namespace is running at Max Capacity
       description: "\nCluster Name: {{$externalLabels.cluster}}\nNamespace: {{$labels.namespace}}\nHPA name: {{$labels.hpa}}\n" 
     expr: |
       ((sum(kube_hpa_spec_max_replicas{hpa=~"devops.*"}) by (hpa,namespace)) - (sum(kube_hpa_status_current_replicas{hpa=~"devops.*"}) by (hpa,namespace))) == 0
     for: 1m
     labels: 
       tech_team: devops_team

   - alert: HPA at MaxCapacity for devops team
     annotations: 
       summary: HPA named {{$labels.hpa}} in {{$labels.namespace}} namespace is running at Max Capacity
       description: "\nCluster Name: {{$externalLabels.cluster}}\nNamespace: {{$labels.namespace}}\nHPA name: {{$labels.hpa}}\n" 
     expr: |
       ((sum(kube_hpa_spec_max_replicas{hpa=~"devops.*"}) by (hpa,namespace)) - (sum(kube_hpa_status_current_replicas{hpa=~"devops.*"}) by (hpa,namespace))) == 0
     for: 1m
     labels: 
       tech_team: devops_team
       

 - name: Pods
   rules:
   - alert: Container restarted
     annotations:
       summary: Container named {{$labels.container}} in {{$labels.pod}} in {{$labels.namespace}} was restarted
       description: "\nCluster Name: {{$externalLabels.cluster}}\nNamespace: {{$labels.namespace}}\nPod name: {{$labels.pod}}\nContainer name: {{$labels.container}}\n" 
     expr: |
       sum(increase(kube_pod_container_status_restarts_total{namespace!="kube-system",pod_template_hash=""}[1m])) by (pod,namespace,container) > 0
     for: 0m
     labels:
       team: devops

   - alert: High Memory Usage of Container 
     annotations: 
       summary: Container named {{$labels.container}} in {{$labels.pod}} in {{$labels.namespace}} is using more than 75% of Memory Limit
       description: "\nCluster Name: {{$externalLabels.cluster}}\nNamespace: {{$labels.namespace}}\nPod name: {{$labels.pod}}\nContainer name: {{$labels.container}}\n" 
     expr: |
       ((( sum(container_memory_working_set_bytes{image!="",container!="POD", namespace!="kube-system",pod!~"devops.*", pod!~"devops.*"}) by (namespace,container,pod)  / sum(container_spec_memory_limit_bytes{image!="",container!="POD",namespace!="kube-system",pod!~"devops.*", pod!~"devops.*"}) by (namespace,container,pod) ) * 100 ) < +Inf )> 75 
     for: 5m
     labels: 
       team: devops

   - alert: High Memory Usage of Container for devops team
     annotations: 
       summary: Container named {{$labels.container}} in {{$labels.pod}} in {{$labels.namespace}} is using more than 75% of Memory Limit
       description: "\nCluster Name: {{$externalLabels.cluster}}\nNamespace: {{$labels.namespace}}\nPod name: {{$labels.pod}}\nContainer name: {{$labels.container}}\n" 
     expr: |
       ((( sum(container_memory_working_set_bytes{image!="",container!="POD", namespace!="kube-system", pod=~"devops.*"}) by (namespace,container,pod)  / sum(container_spec_memory_limit_bytes{image!="",container!="POD",namespace!="kube-system",pod=~"devops.*"}) by (namespace,container,pod) ) * 100 ) < +Inf ) > 75
     for: 5m
     labels: 
       tech_team: devops_team
  
   - alert: High Memory Usage of Container for devops team
     annotations: 
       summary: Container named {{$labels.container}} in {{$labels.pod}} in {{$labels.namespace}} is using more than 75% of Memory Limit
       description: "\nCluster Name: {{$externalLabels.cluster}}\nNamespace: {{$labels.namespace}}\nPod name: {{$labels.pod}}\nContainer name: {{$labels.container}}\n" 
     expr: |
       ((( sum(container_memory_working_set_bytes{image!="",container!="POD", namespace!="kube-system", pod=~"devops.*"}) by (namespace,container,pod)  / sum(container_spec_memory_limit_bytes{image!="",container!="POD",namespace!="kube-system",pod=~"devops.*"}) by (namespace,container,pod) ) * 100 ) < +Inf ) > 75
     for: 5m
     labels: 
       tech_team: devops_team

   - alert: High CPU Usage of Container 
     annotations: 
       summary: Container named {{$labels.container}} in {{$labels.pod}} in {{$labels.namespace}} is using more than 75% of CPU Limit
       description: "\nCluster Name: {{$externalLabels.cluster}}\nNamespace: {{$labels.namespace}}\nPod name: {{$labels.pod}}\nContainer name: {{$labels.container}}\n" 
     expr: |
       ((sum(irate(container_cpu_usage_seconds_total{image!="",container!="POD", namespace!="kube-system",pod !~"devops.*", pod !~"devops.*"}[30s])) by (namespace,container,pod) / sum(container_spec_cpu_quota{image!="",container!="POD", namespace!="kube-system",pod !~"devops.*", pod !~"devops.*"} / container_spec_cpu_period{image!="",container!="POD", namespace!="kube-system",pod!~"devops.*", pod!~"devops.*"}) by (namespace,container,pod) ) * 100)  > 75
     for: 5m
     labels: 
       team: devops

   - alert: High CPU Usage of Container for devops team 
     annotations: 
       summary: Container named {{$labels.container}} in {{$labels.pod}} in {{$labels.namespace}} is using more than 75% of CPU Limit
       description: "\nCluster Name: {{$externalLabels.cluster}}\nNamespace: {{$labels.namespace}}\nPod name: {{$labels.pod}}\nContainer name: {{$labels.container}}\n" 
     expr: |
       ((sum(irate(container_cpu_usage_seconds_total{image!="",container!="POD", namespace!="kube-system", pod=~"devops.*"}[30s])) by (namespace,container,pod) / sum(container_spec_cpu_quota{image!="",container!="POD", namespace!="kube-system", pod=~"devops.*"} / container_spec_cpu_period{image!="",container!="POD", namespace!="kube-system", pod=~"devops.*"}) by (namespace,container,pod) ) * 100)  > 75
     for: 5m
     labels: 
       tech_team: devops_team

   - alert: High CPU Usage of Container for devops team 
     annotations: 
       summary: Container named {{$labels.container}} in {{$labels.pod}} in {{$labels.namespace}} is using more than 75% of CPU Limit
       description: "\nCluster Name: {{$externalLabels.cluster}}\nNamespace: {{$labels.namespace}}\nPod name: {{$labels.pod}}\nContainer name: {{$labels.container}}\n" 
     expr: |
       ((sum(irate(container_cpu_usage_seconds_total{image!="",container!="POD", namespace!="kube-system", pod=~"devops.*"}[30s])) by (namespace,container,pod) / sum(container_spec_cpu_quota{image!="",container!="POD", namespace!="kube-system", pod=~"devops.*"} / container_spec_cpu_period{image!="",container!="POD", namespace!="kube-system", pod=~"devops.*"}) by (namespace,container,pod) ) * 100)  > 75
     for: 5m
     labels: 
       tech_team: devops_team


   - alert: High Persistent Volume Usage
     annotations:
       summary: Persistent Volume named {{$labels.persistentvolumeclaim}} in {{$labels.namespace}} is using more than 75% used.
       description: "\nCluster Name: {{$externalLabels.cluster}}\nNamespace: {{$labels.namespace}}\nPVC name: {{$labels.persistentvolumeclaim}}\n"
     expr: |
       ((((sum(kubelet_volume_stats_used_bytes{})  by (namespace,persistentvolumeclaim))  / (sum(kubelet_volume_stats_capacity_bytes{}) by (namespace,persistentvolumeclaim)))*100) < +Inf ) > 75
     for: 5m
     labels:
       team: devops

 - name: Nodes
   rules:
   - alert: High Node Memory Usage
     annotations:
       summary: Node {{$labels.kubernetes_io_hostname}} has more than 80% memory used. Plan Capcity
       description: "\nCluster Name: {{$externalLabels.cluster}}\Node: {{$labels.kubernetes_io_hostname}}\n" 
     expr: |
       (sum (container_memory_working_set_bytes{id="/",container!="POD"}) by (kubernetes_io_hostname) / sum (machine_memory_bytes{}) by (kubernetes_io_hostname) * 100) > 80
     for: 5m
     labels:
       team: devops

   - alert: High Node CPU Usage
     annotations:
       summary: Node {{$labels.kubernetes_io_hostname}} has more than 80% allocatable cpu used. Plan Capacity.
       description: "\nCluster Name: {{$externalLabels.cluster}}\Node: {{$labels.kubernetes_io_hostname}}\n" 
     expr: |
       (sum(rate(container_cpu_usage_seconds_total{id="/", container!="POD"}[1m])) by (kubernetes_io_hostname) / sum(machine_cpu_cores) by (kubernetes_io_hostname)  * 100) > 80
     for: 5m
     labels:
       team: devops

   - alert: High Node Disk Usage
     annotations:
       summary: Node {{$labels.kubernetes_io_hostname}} has more than 85% disk used. Plan Capacity.
       description: "\nCluster Name: {{$externalLabels.cluster}}\Node: {{$labels.kubernetes_io_hostname}}\n" 
     expr: |
       (sum(container_fs_usage_bytes{device=~"^/dev/[sv]d[a-z][1-9]$",id="/",container!="POD"}) by (kubernetes_io_hostname) / sum(container_fs_limit_bytes{container!="POD",device=~"^/dev/[sv]d[a-z][1-9]$",id="/"}) by (kubernetes_io_hostname)) * 100 > 85
     for: 5m
     labels:
       team: devops
