apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "java-app.fullname" . }}
  labels:
{{ include "java-app.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "java-app.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "java-app.name" . }}
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image.port }}
              protocol: TCP
          {{- if .Values.configvalues }}
          envFrom:
            - configMapRef:
                name: {{ include "java-app.fullname" . }}
          {{- end }}
          {{- if .Values.secrets }}
          volumeMounts:
          - name: credentials
            mountPath: "/etc/secrets"
      volumes:
        - name: credentials
          secret:
            secretName: {{ include "java-app.fullname" . }}     
          {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.image.health_url }}
              port: {{ .Values.image.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.image.health_url }}
              port: {{ .Values.image.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
{{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
