{{- if .Values.alertmanager.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
  namespace: {{ .Values.namespace }}
data:
  config.yml: |-
{{ .Files.Get "configs/alertmanager-config.yaml" | indent 4 }}

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: slack-template
  namespace: {{ .Values.namespace }}
data:
  slack-template-config.tmpl: |-
{{ .Files.Get "configs/slack-template-config.yaml" | indent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alertmanager
  namespace: {{ .Values.namespace }}
  labels:
    app: alertmanager
spec:
  replicas: {{ .Values.alertmanager.replicas }}
  selector:
    matchLabels:
      app: alertmanager
  serviceName: alertmanager-headless
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: prometheus-alertmanager-configmap-reload
        image: "jimmidyson/configmap-reload:v0.5.0"
        imagePullPolicy: "IfNotPresent"
        args:
          - --volume-dir=/etc/alertmanager
          - --webhook-url=http://127.0.0.1:9093/-/reload
        volumeMounts:
          - name: config-volume
            mountPath: /etc/alertmanager
            readOnly: true
      - name: alertmanager
        image: {{ .Values.alertmanager.image }}
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
        args:
          - '--config.file=/etc/alertmanager/config.yml'
          - '--storage.path=/alertmanager'
          {{- if gt .Values.alertmanager.replicas 1.0 }}
          - --cluster.advertise-address=$(POD_IP):9094
          - --cluster.listen-address=0.0.0.0:9094
          {{- end }}
          {{- if gt .Values.alertmanager.replicas 1.0}}
          {{- range $i := until (int .Values.alertmanager.replicas) }}
          - --cluster.peer=alertmanager-{{ $i }}.alertmanager-headless:9094
          {{- end }}
          {{- end }}
        ports:
        - name: alertmanager
          containerPort: 9093
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
        - name: slack-template-volume
          mountPath: /etc/alertmanager-templates
        - name: alertmanager
          mountPath: /alertmanager
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager
      - name: slack-template-volume
        configMap:
          name: slack-template
      - name: alertmanager
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
  labels:
    name: alertmanager
  name: alertmanager
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: alertmanager
  type: {{ .Values.alertmanager.service.type }}
  ports:
  - name: alertmanager
    protocol: TCP
    port: 9093
    targetPort: 9093
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
  labels:
    name: alertmanager
  name: alertmanager-headless
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: alertmanager
  clusterIP: None
  ports:
  - name: alertmanager
    protocol: TCP
    port: 9093
    targetPort: 9093
  {{- if gt .Values.alertmanager.replicas 1.0 }}
  - port: 9094
    targetPort: 9094
    protocol: TCP
    name: cluster-tcp
  - port: 9094
    targetPort: 9094
    protocol: UDP
    name: cluster-udp
  {{- end }}
{{- end }}
