{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {{ toYaml .Values.serviceAccount.serviceAccountAnnotations | nindent 4 }}
  name: monitoring
  namespace: {{ .Values.namespace }}
{{- end }}
